language: ruby
rvm:
  - 2.0.0
  - 1.9.3
matrix:
  allow_failures:
    - rvm: 2.0.0
env: GOVUK_APP_DOMAIN=test
bundler_args: --without development
script:
  - bundle exec rake db:schema:load
  - bundle exec rake spec
before_install:
  - mysql -u root -e "CREATE DATABASE contacts_test"
  - mysql -u root -e "GRANT ALL ON contacts_test.* TO 'contacts'@'localhost' IDENTIFIED BY 'contacts'"
  - cp config/database.travis.yml config/database.yml
branches:
  only:
    - master
